bace:
  proj_dim: 30
  batch_size: 256
  epochs: 100
  dkl_epochs: 20
  ue_method: embsvdkl
  n_inducing_points: 512
  ind_type: 'kmeans'
  dkl_s: s2
  dkl_scale: 1
  decay_dkl: 1e-4
  ll: elbo
  extra_pll: True
  input_model_file: 'models_graphcl/graphcl_80.pth'
bbbp:
  proj_dim: 300
  batch_size: 32
  epochs: 70
  dkl_epochs: 150
  ue_method: embsvdkl
  n_inducing_points: 512
  ind_type: 'kmeans'
  dkl_s: s2
  dkl_scale: 0.1
  decay_dkl: 1e-4
  input_model_file: 'models_graphcl/graphcl_80.pth'
  #input_model_file: 'none'
clintox:
  proj_dim: 30
  batch_size: 256
  epochs: 100
  dkl_epochs: 140
  ue_method: embsvdkl
  n_inducing_points: 512
  ind_type: 'kmeans'
  dkl_s: s2
  dkl_scale: 1
  decay_dkl: 1e-3
  ll: elbo
  extra_pll: False
  input_model_file: 'models_graphcl/graphcl_80.pth'
tox21:
  proj_dim: 30
  epochs: 100
  dkl_epochs: 1
  ue_method: svdkl
  n_inducing_points: 256
  ind_type: 'kmeans'
  dkl_s: s2
  dkl_scale: 1
  decay_dkl: 1e-4
  input_model_file: 'models_graphcl/graphcl_80.pth'
hiv:
  proj_dim: 30
  epochs: 100
  dkl_epochs: 30
  ue_method: svdkl
  n_inducing_points: 512
  ind_type: 'random'
  dkl_s: s2
  dkl_scale: 0.1
  decay: 1e-5
  decay_dkl: 0
  input_model_file: 'models_graphcl/graphcl_80.pth'
muv:
  epochs: 100
  dkl_epochs: 20
  ue_method: svdkl
  dkl_s: s2
  decay: 1e-4
  input_model_file: 'models_graphcl/graphcl_80.pth'
sider:
  epochs: 100
  dkl_epochs: 100
  ue_method: svdkl
  n_inducing_points: 512
  ind_type: 'kmeans'
  dkl_s: s2
  dkl_scale: 0.1
  decay_dkl: 1e-5
  input_model_file: 'models_graphcl/graphcl_80.pth'
esol:
  proj_dim: 300
  batch_size: 64
  epochs: 100
  dkl_epochs: 100
  ue_method: embsvdkl
  n_inducing_points: 1024
  ind_type: 'random'
  dkl_s: s2
  dkl_scale: 1
  decay_dkl: 1e-4
  ll: elbo
  extra_pll: True
  input_model_file: 'models_graphcl/graphcl_80.pth'
  #input_model_file: 'none'
freesolv:
  proj_dim: 300
  batch_size: 128
  epochs: 100
  dkl_epochs: 300
  ue_method: embsvdkl
  n_inducing_points: 1024
  ind_type: 'random'
  dkl_s: s2
  dkl_scale: 1
  decay_dkl: 1e-3
  ll: elbo
  extra_pll: True
  input_model_file: 'models_graphcl/graphcl_80.pth'
  #input_model_file: 'none'
lipophilicity:
  proj_dim: 300
  batch_size: 128
  epochs: 100
  dkl_epochs: 100
  ue_method: embsvdkl
  n_inducing_points: 1024
  ind_type: 'random'
  dkl_s: s2
  dkl_scale: 0.1
  decay_dkl: 1e-5
  ll: elbo
  extra_pll: True
  input_model_file: 'models_graphcl/graphcl_80.pth'
  #input_model_file: 'none'
qm7:
  proj_dim: 300
  batch_size: 128
  epochs: 200
  dkl_epochs: 100
  ue_method: embsvdkl
  n_inducing_points: 1024
  ind_type: 'random'
  dkl_s: s2
  dkl_scale: 10
  decay_dkl: 1e-4
  ll: elbo
  extra_pll: True
  #input_model_file: 'models_graphcl/graphcl_80.pth'
  input_model_file: 'none'
qm8:
  proj_dim: 300
  batch_size: 128
  epochs: 100
  dkl_epochs: 70
  ue_method: embsvdkl
  n_inducing_points: 1024
  ind_type: 'random'
  dkl_s: s2
  dkl_scale: 0.1
  decay_dkl: 1e-3
  ll: elbo
  extra_pll: True
  input_model_file: 'none'
qm9:
  proj_dim: 300
  batch_size: 128
  epochs: 100
  dkl_epochs: 10
  ue_method: embsvdkl
  n_inducing_points: 1024
  ind_type: 'random'
  dkl_s: s2
  dkl_scale: 0.1
  decay_dkl: 1e-5
  ll: elbo
  extra_pll: True
  input_model_file: 'models_graphcl/graphcl_80.pth'
